name: '[PSH] Quality Engineering'

on:
  push:
    branches:
      - master
      - main
      - feature/sonarcloud-coverag

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@next-version
    with:
      nodeLint: true
      nodeTest: true
      reactTest: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_quickorder
      nodeSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
